/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevRouteImport } from './routes/dev'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevTasksRouteImport } from './routes/dev.tasks'
import { Route as DevSprintRouteImport } from './routes/dev.sprint'
import { Route as DevProfileRouteImport } from './routes/dev.profile'
import { Route as DevKanbanRouteImport } from './routes/dev.kanban'
import { Route as DevDashboardRouteImport } from './routes/dev.dashboard'
import { Route as AppTeamsRouteImport } from './routes/app.teams'
import { Route as AppSprintPlanningRouteImport } from './routes/app.sprint-planning'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppKanbanRouteImport } from './routes/app.kanban'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppBacklogRouteImport } from './routes/app.backlog'
import { Route as AppAiCenterRouteImport } from './routes/app.ai-center'

const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevTasksRoute = DevTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DevRoute,
} as any)
const DevSprintRoute = DevSprintRouteImport.update({
  id: '/sprint',
  path: '/sprint',
  getParentRoute: () => DevRoute,
} as any)
const DevProfileRoute = DevProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DevRoute,
} as any)
const DevKanbanRoute = DevKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => DevRoute,
} as any)
const DevDashboardRoute = DevDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DevRoute,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppSprintPlanningRoute = AppSprintPlanningRouteImport.update({
  id: '/sprint-planning',
  path: '/sprint-planning',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppKanbanRoute = AppKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBacklogRoute = AppBacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => AppRoute,
} as any)
const AppAiCenterRoute = AppAiCenterRouteImport.update({
  id: '/ai-center',
  path: '/ai-center',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dev': typeof DevRouteWithChildren
  '/app/ai-center': typeof AppAiCenterRoute
  '/app/backlog': typeof AppBacklogRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/kanban': typeof AppKanbanRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sprint-planning': typeof AppSprintPlanningRoute
  '/app/teams': typeof AppTeamsRoute
  '/dev/dashboard': typeof DevDashboardRoute
  '/dev/kanban': typeof DevKanbanRoute
  '/dev/profile': typeof DevProfileRoute
  '/dev/sprint': typeof DevSprintRoute
  '/dev/tasks': typeof DevTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dev': typeof DevRouteWithChildren
  '/app/ai-center': typeof AppAiCenterRoute
  '/app/backlog': typeof AppBacklogRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/kanban': typeof AppKanbanRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sprint-planning': typeof AppSprintPlanningRoute
  '/app/teams': typeof AppTeamsRoute
  '/dev/dashboard': typeof DevDashboardRoute
  '/dev/kanban': typeof DevKanbanRoute
  '/dev/profile': typeof DevProfileRoute
  '/dev/sprint': typeof DevSprintRoute
  '/dev/tasks': typeof DevTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dev': typeof DevRouteWithChildren
  '/app/ai-center': typeof AppAiCenterRoute
  '/app/backlog': typeof AppBacklogRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/kanban': typeof AppKanbanRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sprint-planning': typeof AppSprintPlanningRoute
  '/app/teams': typeof AppTeamsRoute
  '/dev/dashboard': typeof DevDashboardRoute
  '/dev/kanban': typeof DevKanbanRoute
  '/dev/profile': typeof DevProfileRoute
  '/dev/sprint': typeof DevSprintRoute
  '/dev/tasks': typeof DevTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dev'
    | '/app/ai-center'
    | '/app/backlog'
    | '/app/dashboard'
    | '/app/kanban'
    | '/app/projects'
    | '/app/reports'
    | '/app/settings'
    | '/app/sprint-planning'
    | '/app/teams'
    | '/dev/dashboard'
    | '/dev/kanban'
    | '/dev/profile'
    | '/dev/sprint'
    | '/dev/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/dev'
    | '/app/ai-center'
    | '/app/backlog'
    | '/app/dashboard'
    | '/app/kanban'
    | '/app/projects'
    | '/app/reports'
    | '/app/settings'
    | '/app/sprint-planning'
    | '/app/teams'
    | '/dev/dashboard'
    | '/dev/kanban'
    | '/dev/profile'
    | '/dev/sprint'
    | '/dev/tasks'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/dev'
    | '/app/ai-center'
    | '/app/backlog'
    | '/app/dashboard'
    | '/app/kanban'
    | '/app/projects'
    | '/app/reports'
    | '/app/settings'
    | '/app/sprint-planning'
    | '/app/teams'
    | '/dev/dashboard'
    | '/dev/kanban'
    | '/dev/profile'
    | '/dev/sprint'
    | '/dev/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DevRoute: typeof DevRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/tasks': {
      id: '/dev/tasks'
      path: '/tasks'
      fullPath: '/dev/tasks'
      preLoaderRoute: typeof DevTasksRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/sprint': {
      id: '/dev/sprint'
      path: '/sprint'
      fullPath: '/dev/sprint'
      preLoaderRoute: typeof DevSprintRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/profile': {
      id: '/dev/profile'
      path: '/profile'
      fullPath: '/dev/profile'
      preLoaderRoute: typeof DevProfileRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/kanban': {
      id: '/dev/kanban'
      path: '/kanban'
      fullPath: '/dev/kanban'
      preLoaderRoute: typeof DevKanbanRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/dashboard': {
      id: '/dev/dashboard'
      path: '/dashboard'
      fullPath: '/dev/dashboard'
      preLoaderRoute: typeof DevDashboardRouteImport
      parentRoute: typeof DevRoute
    }
    '/app/teams': {
      id: '/app/teams'
      path: '/teams'
      fullPath: '/app/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sprint-planning': {
      id: '/app/sprint-planning'
      path: '/sprint-planning'
      fullPath: '/app/sprint-planning'
      preLoaderRoute: typeof AppSprintPlanningRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kanban': {
      id: '/app/kanban'
      path: '/kanban'
      fullPath: '/app/kanban'
      preLoaderRoute: typeof AppKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/backlog': {
      id: '/app/backlog'
      path: '/backlog'
      fullPath: '/app/backlog'
      preLoaderRoute: typeof AppBacklogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-center': {
      id: '/app/ai-center'
      path: '/ai-center'
      fullPath: '/app/ai-center'
      preLoaderRoute: typeof AppAiCenterRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiCenterRoute: typeof AppAiCenterRoute
  AppBacklogRoute: typeof AppBacklogRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppKanbanRoute: typeof AppKanbanRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSprintPlanningRoute: typeof AppSprintPlanningRoute
  AppTeamsRoute: typeof AppTeamsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiCenterRoute: AppAiCenterRoute,
  AppBacklogRoute: AppBacklogRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppKanbanRoute: AppKanbanRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSprintPlanningRoute: AppSprintPlanningRoute,
  AppTeamsRoute: AppTeamsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DevRouteChildren {
  DevDashboardRoute: typeof DevDashboardRoute
  DevKanbanRoute: typeof DevKanbanRoute
  DevProfileRoute: typeof DevProfileRoute
  DevSprintRoute: typeof DevSprintRoute
  DevTasksRoute: typeof DevTasksRoute
}

const DevRouteChildren: DevRouteChildren = {
  DevDashboardRoute: DevDashboardRoute,
  DevKanbanRoute: DevKanbanRoute,
  DevProfileRoute: DevProfileRoute,
  DevSprintRoute: DevSprintRoute,
  DevTasksRoute: DevTasksRoute,
}

const DevRouteWithChildren = DevRoute._addFileChildren(DevRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DevRoute: DevRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
